"""create patent claim tables

Revision ID: 43989b4b3b37
Revises: 
Create Date: 2026-06-08 18:10:54.266630
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '43989b4b3b37'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=32), nullable=False),
    sa.Column('application_number_normalized', sa.String(length=32), nullable=True),
    sa.Column('register_number', sa.String(length=32), nullable=True),
    sa.Column('publication_number', sa.String(length=32), nullable=True),
    sa.Column('open_number', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_eng', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('applicant_name', sa.String(length=300), nullable=True),
    sa.Column('ipc_number', sa.String(length=500), nullable=True),
    sa.Column('application_date', sa.String(length=32), nullable=True),
    sa.Column('register_status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetch_status', sa.String(length=50), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_applicant_name'), 'patents', ['applicant_name'], unique=False)
    op.create_index(op.f('ix_patents_application_number'), 'patents', ['application_number'], unique=True)
    op.create_index(op.f('ix_patents_application_number_normalized'), 'patents', ['application_number_normalized'], unique=False)
    op.create_index('ix_patents_ipc_number', 'patents', ['ipc_number'], unique=False)
    op.create_index(op.f('ix_patents_open_number'), 'patents', ['open_number'], unique=False)
    op.create_index(op.f('ix_patents_publication_number'), 'patents', ['publication_number'], unique=False)
    op.create_index(op.f('ix_patents_register_number'), 'patents', ['register_number'], unique=False)
    op.create_index('ix_patents_register_status', 'patents', ['register_status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_independent', sa.Boolean(), nullable=True),
    sa.Column('dependency_claim_numbers', sa.String(length=200), nullable=True),
    sa.Column('source_endpoint', sa.String(length=100), nullable=False),
    sa.Column('source_document_type', sa.String(length=100), nullable=False),
    sa.Column('parser_confidence', sa.Float(), nullable=True),
    sa.Column('parser_method', sa.String(length=50), nullable=True),
    sa.Column('parser_status', sa.String(length=50), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patent_id', 'claim_number', name='uq_claims_patent_claim_number')
    )
    op.create_index('ix_claims_is_independent', 'claims', ['is_independent'], unique=False)
    op.create_index('ix_claims_status', 'claims', ['status'], unique=False)
    op.create_table('claim_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('element_order', sa.Integer(), nullable=False),
    sa.Column('element_text', sa.Text(), nullable=False),
    sa.Column('source_span', sa.Text(), nullable=True),
    sa.Column('parser_confidence', sa.Float(), nullable=True),
    sa.Column('parser_method', sa.String(length=50), nullable=True),
    sa.Column('parser_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'element_order', name='uq_claim_elements_claim_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_elements')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_index('ix_claims_is_independent', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_patents_register_status', table_name='patents')
    op.drop_index(op.f('ix_patents_register_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_publication_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_open_number'), table_name='patents')
    op.drop_index('ix_patents_ipc_number', table_name='patents')
    op.drop_index(op.f('ix_patents_application_number_normalized'), table_name='patents')
    op.drop_index(op.f('ix_patents_application_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_applicant_name'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
